# Supabase configuration for Lovable platform

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://id-preview--76b842c5-34fb-4c76-97fb-ad23c3c90c2d.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reenrollment = false

[edge_functions]
enabled = true

[functions.test-email-connection]
verify_jwt = false

[functions.fetch-latest-email] 
verify_jwt = false